const data = new Date('2023-02-20 13:59:40');
console.log('dia', data.getDate());
console.log('mês', data.getMonth() + 1);
console.log('ano', data.getFullYear());
console.log('hora', data.getHours());
console.log('minuto', data.getMinutes());
console.log('segundo', data.getSeconds());
console.log('milesimo', data.getMilliseconds());
console.log('dia da semana', data.getDay());
//console.log(Date.now());